runtime: java21
env: standard
instance_class: F2

entrypoint: "java -jar build/libs/uniplan-backend-all.jar"
#  shell: "java -jar build/libs/ktor-sample-all.jar"
# ... rest of your app.yaml
#"entrypoint": {
#  "shell": "java -jar ktor-sample-all.jar"
#}

inbound_services:
  - warmup

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: 500ms
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6

# Network settings
network:
  session_affinity: true

# Environment variables
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=512m"
  KTOR_ENV: production
  GOOGLE_APPLICATION_CREDENTIALS: "service-account.json"

# Request handlers
handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: auto
    secure: always

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Resources
resources:
  cpu: 1
  memory_gb: 1.0
  disk_size_gb: 10